"""'update'

Revision ID: 145e337b4f2e
Revises: 7a4fb9fe6f21
Create Date: 2023-03-02 08:39:18.998274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145e337b4f2e'
down_revision = '7a4fb9fe6f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_library', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_library', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
